version: "3"
services:
  simple_flask_on_ecs:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - ..:/project
    image: simple_flask_on_ecs-image
    container_name: simple_flask_on_ecs-container
    tty: true
    env_file: ../.env # shellスクリプト内でも環境変数として使用するため
